// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grbqpuqlltkcwpsubhui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyYnFwdXFsbHRrY3dwc3ViaHVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0MzA5NzQsImV4cCI6MjA4ODAwNjk3NH0.odWXMv07KJJ249XKeR1GRz2xbJGqJruUkvcrz_tiVP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});